### ISSUE TITLE
camera fov and default dist? How to render the output mesh so that it look like the input image most?

### ISSUE THREAD

**Issue by YuQiao0303** [thu-ml/CRM#32]
Hi authors, thank you for this great work!

I wonder how can I render the output mesh, so that the rendered image would look like the input image most? Specifically, what is the camera **fov in degrees,** and default **distance between the camera and the mesh**? or maybe we should scale the mesh first? 

Thank you!!!

**Comment by otakudj** [comment]
Hi, Thank you for the interest @YuQiao0303 

We use the [nvdiffrast](https://nvlabs.github.io/nvdiffrast/) for differential render in training, so if you want the rendered image most like the input image, you need render the output mesh using nvdiffrast. 

For the fov, We render the ground truth image through blender python api like [shap-e](https://github.com/openai/shap-e/blob/50131012ee11c9d2617f3886c10f000d3c7a3b43/shap_e/rendering/blender/blender_script.py), so the fov is the default fov in blender (rad 0.6911112070083618, sorry i can't find the doc specifically saying the default fov, it is the value i export by the script) .

For the distance, our reconstruction model is trained by scale the mesh [[-0.5, 0.5]](https://github.com/openai/shap-e/blob/50131012ee11c9d2617f3886c10f000d3c7a3b43/shap_e/rendering/blender/blender_script.py#L103) to [-0.95, 0.95] as [3dgen](https://arxiv.org/abs/2303.05371). If you want the rendered image most like the input image, you need to set the distance between the camera and the mesh to [2](https://github.com/openai/shap-e/blob/50131012ee11c9d2617f3886c10f000d3c7a3b43/shap_e/rendering/blender/blender_script.py#L127) * 0.95 / 0.5=3.8, or scale the exported mesh by 0.5 / 0.95  and keep the distance at 2.

Looking forward for your reply

**Comment by YuQiao0303** [comment]
> Hi, Thank you for the interest @YuQiao0303
> 
> We use the [nvdiffrast](https://nvlabs.github.io/nvdiffrast/) for differential render in training, so if you want the rendered image most like the input image, you need render the output mesh using nvdiffrast.
> 
> For the fov, We render the ground truth image through blender python api like [shap-e](https://github.com/openai/shap-e/blob/50131012ee11c9d2617f3886c10f000d3c7a3b43/shap_e/rendering/blender/blender_script.py), so the fov is the default fov in blender (rad 0.6911112070083618, sorry i can't find the doc specifically saying the default fov, it is the value i export by the script) .
> 
> For the distance, our reconstruction model is trained by scale the mesh [[-0.5, 0.5]](https://github.com/openai/shap-e/blob/50131012ee11c9d2617f3886c10f000d3c7a3b43/shap_e/rendering/blender/blender_script.py#L103) to [-0.95, 0.95] as [3dgen](https://arxiv.org/abs/2303.05371). If you want the rendered image most like the input image, you need to set the distance between the camera and the mesh to [2](https://github.com/openai/shap-e/blob/50131012ee11c9d2617f3886c10f000d3c7a3b43/shap_e/rendering/blender/blender_script.py#L127) * 0.95 / 0.5=3.8, or scale the exported mesh by 0.5 / 0.95 and keep the distance at 2.
> 
> Looking forward for your reply

Hi author! Thank you for your fast and detailed reply!!!  I really appreciate it!

I test rendering using nvdiffrast, though following your mentioned settings looks a little strange. The image is overall too small and the camera settings seem wrong.   (see right part of the image)

I accidentally found that using an orthogonal camera seems good. (see middle part of the image).

Thank you so much !!! 



![image](https://github.com/user-attachments/assets/12d3257d-8bfc-439c-bde0-3633430c3c45)

**Comment by MontaEllis** [comment]
Can you share the rendering code?
